### ISSUE TITLE
Alternative objects

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/Leipzig2016#2]
Some ideas, we ma just pick one or two. Specially for the Manipulation Test and the EEGPSR in Advanced Manipulation

- Cordless phone (can we get some old ones?)
- A book
- A pen/pencil
- An egg  (boiled for security)
- A salt shaker
- A hair/dishwasher brush

**Comment by LoyVanBeek** [comment]
Objects are bought, with an 'egg' in there.
